package(default_visibility = ["//visibility:public"])

java_binary(
    name = "two_sum",
    jvm_flags = ["-ea"],
    srcs = glob(["*.java"]),
    main_class = "com.noosxe.problems.two_sum.TwoSum"
)
