package(default_visibility = ["//visibility:public"])

java_binary(
    name = "run_length_dec",
    jvm_flags = ["-ea"],
    srcs = glob(["*.java"]),
    main_class = "com.noosxe.problems.run_length_dec.RunLengthDec"
)
